title: Navigating the Digital World
description: A website 
theme: just-the-docs

url: https://navigatingthedigitalworld.com/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
