title: Navigating the Digital World
description: A website 
theme: just-the-docs

url: https://navigatingthedigitalworld.com/

# Color scheme supports "light" (default) and "dark"
color_scheme: light

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
